# Generated by Django 3.1.1 on 2020-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('number', models.CharField(blank=None, max_length=30, primary_key=True, serialize=False)),
                ('expirationMonth', models.IntegerField(blank=None, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')])),
                ('expirationYear', models.IntegerField(blank=None)),
                ('cvv', models.IntegerField(blank=None)),
                ('type', models.CharField(blank=None, choices=[('debitcard', 'debitcard'), ('creditcard', 'creditcard')], max_length=50)),
                ('amount', models.IntegerField(default=None)),
                ('currency', models.CharField(default=None, max_length=10)),
                ('authorization_code', models.CharField(default=None, max_length=12)),
            ],
        ),
    ]
